export let classEngravings = [
    {text: "Barrage enhancement", value: "Barrage enhancement", class: "Artillerist"},
    {text: "Berserker's technique", value: "Berserker's technique", class: "Berserker"},
    {text: "Blessed aura", value: "Blessed aura", class: "Paladin"},
    {text: "Combat readiness", value: "Combat readiness", class: "Gunlancer"},
    {text: "Death strike", value: "Death strike", class: "Sharpshooter"},
    {text: "Deathblow", value: "Deathblow", class: "Striker"},
    {text: "Demonic impulse", value: "Demonic impulse", class: "Shadowhunter"},
    {text: "Desperate salvation", value: "Desperate salvation", class: "Bard"},
    {text: "Energy overflow", value: "Energy overflow", class: "Soulfist"},
    {text: "Enhanced weapon", value: "Enhanced weapon", class: "Deadeye"},
    {text: "Esoteric flurry", value: "Esoteric flurry", class: "Striker"},
    {text: "Esoteric skill enhancement", value: "Esoteric skill enhancement", class: "Wardancer"},
    {text: "Firepower enhancement", value: "Firepower enhancement", class: "Artillerist"},
    {text: "First intention", value: "First intention", class: "Wardancer"},
    {text: "Igniter", value: "Igniter", class: "Sorceress"},
    {text: "Judgment", value: "Judgement", class: "Paladin"},
    {text: "Lone knight", value: "lone knight", class: "Gunlancer"},
    {text: "Loyal companion", value: "Loyal companion", class: "Sharpshooter"},
    {text: "Mayhem", value: "Mayhem", class: "Berserker"},
    {text: "Peacemaker", value: "Peacemaker", class: "Gunslinger"},
    {text: "Perfect suppression", value: "Perfect suppression", class: "Shadowhunter"},
    {text: "Pistoleer", value: "Pistoleer", class: "Deadeye"},
    {text: "Reflux", value: "Reflux", class: "Sorceress"},
    {text: "Remaining energy", value: "Remaining energy", class: "Deathblade"},
    {text: "Robust spirit", value: "Robust spirit", class: "Soulfist"},
    {text: "Shock training", value: "Shock training", class: "Scrapper"},
    {text: "Surge", value: "Surge", class: "Deathblade"},
    {text: "Time to hunt", value: "Time to hunt", class: "Gunslinger"},
    {text: "True courage", value: "True courage", class: "Bard"},
    {text: "Ultimate skill: Taijutsu", value: "Ultimate skill: Taijutsu", class: "Scrapper"},
]