export let classEngravings = [
    {text: "Barrage enhancement", value: "Barrage enhancement"},
    {text: "Berserker's technique", value: "Berserker's technique"},
    {text: "Blessed aura", value: "Blessed aura"},
    {text: "Combat readiness", value: "Combat readiness"},
    {text: "Death strike", value: "Death strike"},
    {text: "Deathblow", value: "Deathblow"},
    {text: "Demonic impulse", value: "Demonic impulse"},
    {text: "Desperate salvation", value: "Desperate salvation"},
    {text: "Energy overflow", value: "Energy overflow"},
    {text: "Enhanced weapon", value: "Enhanced weapon"},
    {text: "Esoteric flurry", value: "Esoteric flurry"},
    {text: "Esoteric skill enhancement", value: "esoteric skill enhancement"},
    {text: "Firepower enhancement", value: "Firepower enhancement"},
    {text: "First intention", value: "First intention"},
    {text: "Igniter", value: "Igniter"},
    {text: "Judgment", value: "Judgement"},
    {text: "Lone knight", value: "lone knight"},
    {text: "loyal companion", value: "Loyal companion"},
    {text: "Mayhem", value: "Mayhem"},
    {text: "Peacemaker", value: "Peacemaker"},
    {text: "Perfect suppression", value: "Perfect suppression"},
    {text: "Pistoleer", value: "Pistoleer"},
    {text: "Reflux", value: "Reflux"},
    {text: "Remaining energy", value: "Remaining energy"},
    {text: "Robust spirit", value: "Robust spirit"},
    {text: "Shock training", value: "Shock training"},
    {text: "Surge", value: "Surge"},
    {text: "Time to hunt", value: "Time to hunt"},
    {text: "true courage", value: "True courage"},
    {text: "Ultimate skill: Taijutsu", value: "Ultimate skill: Taijutsu"},
]