export let combatEngravings = [
    {text: "", value: ""},
    {text: "Adrenaline", value: "Adrenaline"},
    {text: "All-out attack", value: "All-out attack"},
    {text: "Ambush master", value: "Ambush master"},
    {text: "Awakening", value: "Awakening"},
    {text: "Barricade", value: "Barricade"},
    {text: "Broken bone", value: "Broken bone"},
    {text: "Contender", value: "Contender"},
    {text: "Crisis evasion", value: "Crisis Evasion"},
    {text: "Crushing fist", value: "Crushing fist"},
    {text: "Cursed Doll", value: "Cursed doll"},
    {text: "Disrespect", value: "Disrespect"},
    {text: "Divine protection", value: "Divine Protection"},
    {text: "Drops of ether", value: "Drops of ether"},
    {text: "Emergency rescue", value: "Emergency rescue"},
    {text: "Enhanced shield", value: "Enhanced shield"},
    {text: "Ether predator", value: "Ether predator"},
    {text: "Expert", value: "Expert"},
    {text: "Explosive expert", value: "Explosive expert"},
    {text: "Fortitude", value: "Fortitude"},
    {text: "Grudge", value: "Grudge"},
    {text: "Heavy armour", value: "Heavy armour"},
    {text: "Hit master", value: "Hit master"},
    {text: "Increased mass", value: "Increased mass"},
    {text: "Keen blunt weapon", value: "Keen blunt weapon"},
    {text: "Lightning fury", value: "Lightning fury"},
    {text: "MP efficiency increase", value: "MP efficiency increase"},
    {text: "Magick stream", value: "Magick stream"},
    {text: "Master brawler", value: "master brawler"},
    {text: "Master of escape", value: "Master of escape"},
    {text: "Master's tenacity", value: "Master's tenacity"},
    {text: "Max mp increase", value: "Max mp increase"},
    {text: "Necromancy", value: "Necromancy"},
    {text: "Precise dagger", value: "Precise dagger"},
    {text: "Preemptive strike", value: "Preemptive strike"},
    {text: "Propulsion", value: "Propulsion"},
    {text: "Raid captain", value: "Raid captain"},
    {text: "Shield piercing", value: "Shield piercing"},
    {text: "Sight focus", value: "Sight focus"},
    {text: "Spirit absorption", value: "Spirit absorption"},
    {text: "Stabilized status", value: "Stabilized status"},
    {text: "Strong will", value: "Strong will"},
    {text: "Super charge", value: "Super charge"},
    {text: "Vital point hit", value: "Vital point hit"},
]