export let usefulEngravings = [
    {text: "", value: ""},
    {text: "Adrenaline", value: "Adrenaline"},
    {text: "All-out attack", value: "All-out attack"},
    {text: "Ambush master", value: "Ambush master"},
    {text: "Awakening", value: "Awakening"},
    {text: "Barricade", value: "Barricade"},
    {text: "Cursed Doll", value: "Cursed doll"},
    {text: "Expert", value: "Expert"},
    {text: "Grudge", value: "Grudge"},
    {text: "Heavy armour", value: "Heavy armour"},
    {text: "Hit master", value: "Hit master"},
    {text: "Increased mass", value: "Increased mass"},
    {text: "Keen blunt weapon", value: "Keen blunt weapon"},
    {text: "Master's tenacity", value: "Master's tenacity"},
    {text: "Precise dagger", value: "Precise dagger"},
    {text: "Preemptive strike", value: "Preemptive strike"},
    {text: "Raid captain", value: "Raid captain"},
    {text: "Sight focus", value: "Sight focus"},
    {text: "Spirit absorption", value: "Spirit absorption"},
    {text: "Stabilized status", value: "Stabilized status"},
    {text: "Super charge", value: "Super charge"},
]